organizer/urls.py
from django.urls import path

from . import views

app_name = 'organizer'
urlpatterns = [
    path('', views.login, name='login'),
    path('logout', views.logout_view, name='logout'),
    path("makeParty", views.GetParty, name="form"),
    path("addAvil", views.GetAvil, name="addAvil"),
    path('watchparties', views.WatchParties, name='watchparties'),
    path('addMovie', views.addMovie, name='addMovie'),
    path('addUser', views.addUser, name='addUser'),
    path('createFriendGroup', views.createFriendGroup, name = 'createFriendGroup'),
    path('<int:pk>/', views.DetailView, name='detail'),
    path('kickUser', views.kickUser, name='kickUser'),
    path('getComment', views.GetComment, name='getComment'),
    path('deleteComment', views.deleteComment, name='deleteComment'),
    path('deleteWatchParties', views.deleteWatchParty, name='deleteWatchParty'),
    path('favorites', views.favoritesView, name='favorites'),
    path('addFav', views.addFavorite, name='addFav'),
    path('rmFav', views.rmFavorite, name='rmFav'),
    path('rmAvilRange', views.rmAvilRange, name='rmAvilRange'),
    path('addFriendGroup', views.addFriendGroup, name='addFriendGroup'),
    path('finalWP', views.finalWP, name='finalWP')
]

watchparty/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('organizer.urls')),
    path('accounts/', include('allauth.urls')),
]

organizer/models.py
from imdb import Cinemagoer
from django.db import models
from django.contrib.auth.models import User


class Watchparty(models.Model):
    account = models.ForeignKey(User, on_delete=models.CASCADE)
    title_text = models.CharField(max_length=200)
    start_date = models.DateField(auto_now=False)
    end_date = models.DateField(auto_now=False)
    def __str__(self):
        return self.title_text

    def valid_date_range(self):
        return self.end_date >= self.start_date

class FinalizedWatchparty(models.Model):
    watchparty = models.ForeignKey(Watchparty, on_delete=models.CASCADE)
    selected_time = models.DateTimeField(auto_now=False, null=True)
    selected_movie = models.CharField(max_length=200, null=True)

class AddedUser(models.Model):
    account = models.ForeignKey(User, on_delete=models.CASCADE)
    watchparty = models.ForeignKey(Watchparty, on_delete=models.CASCADE)
    def __str__(self):
        return self.account.username + " in " + self.watchparty.title_text

class FriendGroup(models.Model):
    owner = models.ForeignKey(User, on_delete = models.CASCADE)
    group_name = models.CharField(max_length = 200)
    def __str__(self):
        return self.group_name

class FriendGroupMember(models.Model):
    fg = models.ForeignKey(FriendGroup, on_delete= models.CASCADE)
    fg_member = models.ForeignKey(User, on_delete= models.CASCADE)
    def __str__(self):
        return self.fg_member.username + " in " + self.fg.group_name

class AvailabilityRange(models.Model):
    account = models.ForeignKey(User, on_delete=models.CASCADE)
    watchparty = models.ForeignKey(Watchparty, on_delete=models.CASCADE)
    start_time = models.DateTimeField(auto_now=False)
    end_time = models.DateTimeField(auto_now=False)

    def valid_time_range(self):
        if self.end_time <= self.start_time:
            return False
        if self.watchparty.start_date.strftime('%Y-%m-%d') > self.start_time.strftime('%Y-%m-%d') or self.watchparty.end_date.strftime('%Y-%m-%d') < self.end_time.strftime('%Y-%m-%d'):
            return False
        return True
    def __str__(self):
        return self.account.username + "'s range for " + self.watchparty.title_text


class MovieSearcher(models.Model):
    account = models.ForeignKey(User, on_delete=models.CASCADE)
    watchparty = models.ForeignKey(Watchparty, on_delete=models.CASCADE)
    search = models.CharField(max_length=100)

    def __str__(self):
        return self.account.username + " votes for " + self.search + " in " + self.watchparty.title_text


class ListOfMovies(models.Model):
    x = models.CharField(max_length=100)


class FavoriteMovie(models.Model):
    account = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.CharField(max_length=200)
    def __str__(self):
        return self.movie

class Comment(models.Model):
    account = models.ForeignKey(User, on_delete=models.CASCADE)
    watchparty = models.ForeignKey(Watchparty, on_delete=models.CASCADE)
    text = models.CharField(max_length=10000)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.account.username + "'s comment in " + self.watchparty.title_text + " on " + self.pub_date

class Images(models.Model):
    image = models.ImageField(upload_to = 'pics/%y/%m/%d/')
    title = models.CharField(max_length = 150)
    sub_title = models.CharField(max_length = 100)

    def __Str__(self):
        return self.title

organizer/forms.py
from django.forms import ModelForm, Textarea, DateInput
from .models import Watchparty, AddedUser, AvailabilityRange, MovieSearcher, Comment
from .widget import DatePickerInput, DateTimePickerInput
from django import forms


class CreateWatchParty(ModelForm):
    class Meta:
        model = Watchparty
        fields = "__all__"
        widgets = {
            'Title': Textarea(),
            'start_date': DateInput(attrs={'type': 'date'}),
            'end_date': DateInput(attrs={'type': 'date'})
        }
        exclude = ['account']


class CreateAddedUser(ModelForm):
    class Meta:
        model = AddedUser
        fields = "__all__"


class CreateAvailabilityRange(ModelForm):
    class Meta:
        model = AvailabilityRange
        fields = "__all__"
        widgets = {
            'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%H:%M'),
            'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%H:%M')
        }
        exclude = ['account', 'watchparty']


class CreateMovieSearch(ModelForm):
    class Meta:
        model = MovieSearcher
        fields = "__all__"
        widgets = {
            'Movie Title:': Textarea()
        }

class CreateComment(ModelForm):
    class Meta:
        model = Comment
        fields = "__all__"
        widgets = {
            'text': Textarea()
        }
        exclude = ['account', 'watchparty']

class DateTimeForm(forms.Form):
    date_field = forms.DateField(widget=DatePickerInput, required=False)
    date_time_field = forms.DateTimeField(widget=DateTimePickerInput, required=False)

organizer/views.py
from imdb import Cinemagoer
from django.shortcuts import get_object_or_404, render, redirect
from django.views import generic
from .forms import CreateWatchParty, CreateAddedUser, CreateAvailabilityRange, CreateMovieSearch, CreateComment, DateTimeForm
from django.http import HttpResponseRedirect, HttpRequest, HttpResponse
from .models import Watchparty, MovieSearcher, ListOfMovies, AddedUser, Comment, AvailabilityRange, FavoriteMovie, FinalizedWatchparty, FriendGroup, FriendGroupMember, Images
from django.urls import reverse
from django.utils import timezone
from collections import Counter
from django.contrib.auth import logout
from django.contrib.auth.models import User
import datetime
from django.contrib import messages

def validate(date_text):
    try:
        datetime.datetime.strptime(date_text, '%Y-%m-%d %H:%M')
        return True
    except ValueError:
        return False

def login(request):
    return render(request, 'organizer/login.html', {})


def logout_view(request):
    logout(request)
    return render(request, 'organizer/login.html', {})


def WatchParties(request):
    invitedWatchParties = []
    for party in AddedUser.objects.filter(account=request.user):
        invitedWatchParties.append(party.watchparty)
    return render(request,'organizer/watchparties.html',{"watchparties_list": Watchparty.objects.order_by('title_text'), "invitedWatchParties": invitedWatchParties})

def finalWP(request):
    watchparty = Watchparty.objects.get(pk=request.POST['watchpartyID'])
    finWP = FinalizedWatchparty(watchparty=watchparty, selected_time=None, selected_movie=None)
    if FinalizedWatchparty.objects.filter(watchparty=watchparty).exists():
        finWP = FinalizedWatchparty.objects.get(watchparty=watchparty)
    if request.POST['date_time_field'] != '':
        finWP.selected_time = request.POST['date_time_field']
    if 'final_movie' in request.POST:
        finWP.selected_movie = request.POST['final_movie']
    finWP.save()
    return HttpResponseRedirect(reverse('organizer:detail', args=(request.POST['watchpartyID'],)))

def favoritesView(request):
    favorites = dict.fromkeys(FavoriteMovie.objects.filter(account=request.user))
    for movie in favorites.keys():
        sameTaste = FavoriteMovie.objects.filter(movie=movie).exclude(account=request.user)
        favorites[movie] = sameTaste
    searchResults = []
    if "search_box" in request.GET:
        searchResults = searchMovie(request.GET['search_box'])
    return render(request, 'organizer/favorites.html', {"favorites": favorites, "searchResults": searchResults})

def DetailView(request, pk):
    watchparty = Watchparty.objects.get(pk=pk)
    sharedRangesTime = []
    finalizedWP = None

    allUsers = set()
    for range in AvailabilityRange.objects.filter(watchparty = watchparty):
        sharedRangesTime.append([range.start_time,range.end_time,range.account.username])
        allUsers.add(range.account.username)
    startAndEndRange = []

    if len(sharedRangesTime) > 0:
        sharedRangesTime.sort(key=lambda y: y[0])
        for i in sharedRangesTime:
            defaultStartTime = i[0]
            defaultEndTime = i[1]
            users = set()
            for j in sharedRangesTime:
                if defaultStartTime <= j[1] and j[0] <= defaultEndTime:
                    users.add(j[2])
                    if j[0] > defaultStartTime:
                        defaultStartTime = j[0]
                    if j[1] < defaultEndTime:
                        defaultEndTime = j[1]
            if len(users) == len(allUsers):
                startAndEndRange.append(defaultStartTime)
                startAndEndRange.append(defaultEndTime)
                break

    '''
    if len(sharedRangesTime) > 0:
        defaultStartTime = sharedRangesTime[0][0]
        defaultEndTime = sharedRangesTime[0][1]
        for i in sharedRangesTime:
            if i[0] > defaultStartTime:
                defaultStartTime = i[0]
            if i[1] < defaultEndTime:
                defaultEndTime = i[1]
        startAndEndRange.append(defaultStartTime)
        startAndEndRange.append(defaultEndTime)
    '''
    searchResults = []
    editingFin = False
    if "search_box" in request.GET:
        searchResults = searchMovie(request.GET['search_box'])
    if "editFin" in request.GET:
        editingFin = True
        
    myFriendGroups = FriendGroup.objects.filter(owner = request.user)

    finWPDateForm = DateTimeForm()
    if FinalizedWatchparty.objects.filter(watchparty=watchparty).exists():
        finalizedWP = FinalizedWatchparty.objects.get(watchparty=watchparty)
        
    return render(request, "organizer/detail.html",
                  {"watchparty": watchparty, "comments": Comment.objects.filter(watchparty=watchparty).order_by("-pub_date"), "users": User.objects.all(), "userVotes": getUsersVotes(request.user),
                   "search": getMovieVotes(), "searchResults": searchResults, "allowedUsers": getAllowedUsers(watchparty), "sharedRange":startAndEndRange, "finalizedWP": finalizedWP, "finWPForm": finWPDateForm, "editingFin": editingFin,  "myFriendGroups": myFriendGroups})


def searchMovie(searchTerm):
    ia = Cinemagoer()
    searchResultsObjects = ia.search_movie(searchTerm)
    searchResults = set()
    for i in range(len(searchResultsObjects)):
        searchResults.add(searchResultsObjects[i]["title"])
    return searchResults

def getAllowedUsers(watchparty):
    allowedUsers = []
    allowedUsers.append(watchparty.account)
    for user in watchparty.addeduser_set.all():
        allowedUsers.append(user.account)
    return allowedUsers

def getUsersVotes(user):
    usersVotes = []
    for movieVote in MovieSearcher.objects.filter(account=user):
        usersVotes.append(movieVote.search)
    return usersVotes

def getMovieVotes():
    full = {}
    for movieVote in MovieSearcher.objects.all():
        if (movieVote.watchparty, movieVote.search) in full.keys():
            full[(movieVote.watchparty, movieVote.search)] += 1
        else:
            full[(movieVote.watchparty, movieVote.search)] = 1
    return full


def GetParty(request):
    if request.method == "POST":
        form = CreateWatchParty(request.POST)
        form.instance.account = request.user
        obj = form.save(commit=False)
        if obj.valid_date_range():
            obj.save()
        return redirect("/watchparties")
    else:
        form = CreateWatchParty()
    return render(request, "organizer/check.html", {"form": form})


def GetAvil(request):
    if request.method == "POST":
        form = CreateAvailabilityRange(request.POST)
        form.instance.account = User.objects.get(pk=request.POST['userID'])
        form.instance.watchparty = Watchparty.objects.get(pk=request.POST['watchpartyID'])
        obj = form.save(commit=False)
        if obj.valid_time_range():
            obj.save()
        else:
            messages.add_message(request, messages.ERROR, 'Error: Availability Range Not Valid!')
        return HttpResponseRedirect(reverse('organizer:detail', args=(request.POST['watchpartyID'],)))
    else:
        form = CreateAvailabilityRange()
    return render(request, "organizer/avilPost.html",
                  {"form": form, "watchpartyID": request.GET['watchpartyID'], "userID": request.GET['userID']})

def rmAvilRange(request):
    watchpartyID = request.POST['watchpartyID']
    if 'avilRangeID' not in request.POST:
        messages.add_message(request, messages.ERROR, 'Error: No Availability Range Selected!')
        return HttpResponseRedirect(reverse('organizer:detail', args=(watchpartyID,)))
    avilRange = AvailabilityRange.objects.get(pk=request.POST['avilRangeID'])
    avilRange.delete()
    return HttpResponseRedirect(reverse('organizer:detail', args=(watchpartyID,)))

def addUser(request):
    watchpartyID = request.POST['watchpartyID']
    userID = request.POST['userID']
    user = User.objects.get(pk=userID)
    watchparty = Watchparty.objects.get(pk=watchpartyID)
    if watchparty.account.username == user.username:
        messages.add_message(request, messages.ERROR, "Error: User is the Owner!")
        return HttpResponseRedirect(reverse('organizer:detail', args=(watchpartyID,)))
    if AddedUser.objects.filter(account=user, watchparty=watchparty).exists():
        messages.add_message(request, messages.ERROR, "Error: User already Added!")
        return HttpResponseRedirect(reverse('organizer:detail', args=(watchpartyID,)))
    au = AddedUser(account=user, watchparty=watchparty)
    au.save()
    return HttpResponseRedirect(reverse('organizer:detail', args=(watchpartyID,)))

def createFriendGroup(request):
    watchpartyID = request.POST['watchpartyID']
    userID = request.POST['userID']
    user = User.objects.get(pk = userID)
    fgName = request.POST['fgName']
    friendGroup = FriendGroup(owner = user, group_name = fgName)
    friendGroup.save()
    return HttpResponseRedirect(reverse('organizer:detail', args=(watchpartyID,)))

def addFriendGroup(request):
    watchpartyID = request.POST['watchpartyID']
    watchparty = Watchparty.objects.get(pk = watchpartyID)
    fg = FriendGroup.objects.get(pk=request.POST['fgID'])
    for fgMember in FriendGroupMember.objects.filter(fg = fg):
        user = fgMember.fg_member
        if watchparty.account.username == user.username:
            continue
        if AddedUser.objects.filter(account=user, watchparty=watchparty).exists():
            continue
        au = AddedUser(account=user, watchparty=watchparty)
        au.save()
    return HttpResponseRedirect(reverse('organizer:detail', args=(watchpartyID,)))

def kickUser(request):
    watchpartyID = request.POST['watchpartyID']
    userID = request.POST['kickedUserID']
    user = User.objects.get(pk=userID)
    watchparty = Watchparty.objects.get(pk=watchpartyID)
    if watchparty.account.username == user.username:
        messages.add_message(request, messages.ERROR, "Error: You Tried to Kick the Owner!")

organizer/templates/organizer/addedUsers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>Enter authorized users:</h2>
    <form method = "post">
        <table>
            {{ form }}
        </table>
        {% csrf_token %}
        <button type = "submit" class = "btn btn-dark"> Post</button>
    </form>
</body>
</html>

organizer/templates/organizer/avilPost.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load socialaccount %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div class="text-center">
        <h1>Enter availiability:</h1>
    <form method = "post">
        <input type="hidden" name="watchpartyID" value = "{{ watchpartyID }}">
        <input type="hidden" name="userID" value = "{{ userID }}">
        
        <div class="center"
        <table>
            {{ form }}
        </table>
    </div>
        {% csrf_token %}
        <br>
        <button type = "submit" class = "btn btn-dark"> Post</button>
    </form>
    </div>
</body>
</html>

organizer/templates/organizer/index.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Watch Party Organizer</title>
</head>
<body>
    <h1> Watch Party! </h1>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>

<!--
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}



{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'organizer/style.css' %}">



-->

organizer/templates/organizer/watchparties.html
<!DOCTYPE html>

{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load socialaccount %}
<!--<link rel="stylesheet" type="text/css" href="{% static 'organizer/style.css' %}">-->
<html lang="en">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a href="{% url 'organizer:login' %}" class="navbar-brand">WatchParty</a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse"> 
                <div class="navbar-nav">            
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            WatchParties
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'organizer:watchparties' %}">My WatchParties</a></li>
                            <li><a class="dropdown-item" href="{% url 'organizer:form' %}">Create WatchParty</a></li>
                          
                        </ul>
                    </li>
                    <a class="nav-link favorites" aria-current="page" href="{% url 'organizer:favorites' %}" role="button"> Favorites </a>
    
                </div>
                <div class="navbar-nav ms-auto">
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Hi {{user}}</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'organizer:logout' %}">Logout</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    

<div class="d-flex flex-column align-items-center justify-content-center">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <meta charset="UTF-8">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
    <!--
    <nav class="navbar navbar-expand-lg navbar-light bg-light ms-auto">
        <a class="btn btn-secondary md" href="{% url 'organizer:login' %}" role="button">Home</a>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="watchpartyDropDown" data-bs-toggle="dropdown" aria-expanded="false">
            Watchparties
          </button>
          <ul class="dropdown-menu" aria-labelledby="watchparties">
            <li><a class="dropdown-item" href="{% url 'organizer:watchparties' %}">My Watchparties</a></li>
            <li><a class="dropdown-item" href="{% url 'organizer:form' %}">Create Watchparty</a></li>
          </ul>
        </div>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="accountDropDown" data-bs-toggle="dropdown" aria-expanded="false">
            Account
          </button>
          <ul class="dropdown-menu" aria-labelledby="account">
            <li><a class="dropdown-item" href="{% url 'organizer:favorites' %}">Favorites</a></li>
            <li><a class="dropdown-item" href="{% url 'organizer:logout' %}">Logout</a></li>
          </ul>
        </div>
    </nav>
    -->

    <script>
    function popupConfirm() {
      var myPopup = new bootstrap.Modal(document.getElementById("popUp"));
      myPopup.show();
    }
    </script>

    <!-- <p class = "h1 text-center"> {{user}}'s Watch Parties</p> -->
    <style>      
        /* Some custom styles*/
        .main-content{
            min-height: 230px;
            background: #dbdfe5;
        }
        .sidebar-content{
            min-height: 230px;
            background: #b4bac0;
        }
        .dark-blues {
            background: #7474BF;  /* fallback for old browsers */
            background: -webkit-linear-gradient(to right, #348AC7, #7474BF);  /* Chrome 10-25, Safari 5.1-6 */
            background: linear-gradient(to right, #348AC7, #7474BF); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
            
            border: 3px solid #eee;
            padding: 15px;
            margin-bottom: 15px;
        } 
        .redark-blues {
            background: #7474BF;  /* fallback for old browsers */
            background: -webkit-linear-gradient(to left, #348AC7, #7474BF);  /* Chrome 10-25, Safari 5.1-6 */
            background: linear-gradient(to left, #348AC7, #7474BF); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
            
            border: 3px solid #eee;
            padding: 15px;
            margin-bottom: 15px;
        } 
        .btn-cool-blues {
            background: #2193b0;  /* fallback for old browsers */
            background: -webkit-linear-gradient(to right, #6dd5ed, #2193b0);  /* Chrome 10-25, Safari 5.1-6 */
            background: linear-gradient(to right, #6dd5ed, #2193b0); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
            color: #fff;
            border: 3px solid #eee;
        }
    </style>
</head>
<body>
    <div class="container mt-3">
        <div class="row">
            <div class="col-sm-6">
                <div class="main-content" style="border-style: outset; border-width: 6px;">
                    <h1 class = "text-center dark-blues" style="padding: 10px 10px 10px 10px; background-color: whitesmoke; text-shadow: 1px 1px 5px whitesmoke;"> My WatchParties</h1>
                    {% if watchparties_list %}
                        <div class="m-4">
                            <ul class = "list-group">
                                {% for watchparty in watchparties_list %}
                                    {% if watchparty.account == user  %}
                                        <form method="POST" action = "{% url 'organizer:deleteWatchParty' %}" >
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="col-sm-10">
                                                    <li class="list-group-item text-center"><a href="{% url 'organizer:detail' watchparty.id %}">{{ watchparty.title_text }}</a>: {{ watchparty.start_date }} to {{ watchparty.end_date }}</li>
                                                </div>
                                                <div class="col-sm-2">
                                                <button type = "button" id="myBtn" style="float:right" class="btn btn-danger" name="deletedID" value="{{ watchparty.id }}" onclick="popupConfirm()"> Delete </button>
                                               <!-- Modal HTML,  sorry for the messed up indentation-->
                        <div id="popUp" class="modal fade" tabindex="-1">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">Delete This WatchParty?</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                                    </div>
                                    <div class="modal-body">
                                        <p>Are you sure you would like to delete?</p>
                                        <p class="text-secondary"><small>This action cannot be undone!</small></p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                        <button type="submit" class="btn btn-danger" name="deletedID" value="{{ watchparty.id }}">Delete</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                                                </div>
                                            </div>
                                        </form>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </div>
                    {% else %}
                        <p>No WatchParties are available.</p>
                    {% endif %}
                </div>
            </div>
            <div class="col-sm-6">
                <div class="sidebar-content" style="border-style: outset; border-width: 6px;">
                    <h1 class = "text-center redark-blues" style="padding: 10px 10px 10px 10px; background-color: whitesmoke; text-shadow: 1px 1px 5px whitesmoke;"> WatchParties I'm In </h1>
                    {% if invitedWatchParties %}
                        <ul class = "list-group">
                            {% for invitedParty in invitedWatchParties %}
                                <li class="list-group-item text-center"><a href="{% url 'organizer:detail' invitedParty.id %}">{{invitedParty.title_text }}</a>: {{invitedParty.start_date }} to {{invitedParty.end_date }}</li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p class="text-center">No invited parties are available.</p>
                    {% endif %}
                </div>
            </div>
            <div>
                <br>
            </div>
            <button type="button" class="btn btn-cool-blues" onclick= "location.href='{% url 'organizer:form' %}'">Create WatchParty</button>
            
        </div>
    </div>
</body>
</div>
</html>